//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaAndNubi.Data.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int Id { get; set; }
        public int Id_pet { get; set; }
        public byte[] Img { get; set; }
        public string Discription { get; set; }
        public int Id_person { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
