//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaAndNubi.Data.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ra
    {
        public int Id { get; set; }
        public string Img { get; set; }
        public string Discription { get; set; }
    }
}
